export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const HOME_ROUTE = '/'
export const BASKET_ROUTE = '/basket'
export const BOOK_ROUTE = '/book'
export const PROFILE_ROUTE = '/profile'